Fix completion
wvffle/mineflayer-dashboard pull request #12
Opened 2020-10-23 16:08 UTC by GroobleDierne

Fix #11

2020-10-23 16:11 UTC, GroobleDierne commented
There is still a bug, if you try to complete with no text it will work but you  won't be able to stop to complete

2020-10-23 16:22 UTC, GroobleDierne commented
Okay it's done

2020-10-24 11:07 UTC, wvffle requested changes

2020-10-24 11:07 UTC, wvffle commented on index.js
> +            resolve((matches || []))
There is one pair of unnecessary parenthesis left

2020-10-24 11:07 UTC, wvffle commented on index.js
> +const { match } = require('assert')
Unused variable

2020-10-24 11:07 UTC, wvffle commented on index.js
> +            if (matches == null || matches[0] == undefined) resolve([])
No newline before if, also I consider single line if statements without `{}` as unreadable in most cases

2020-10-24 11:08 UTC, wvffle commented
Later today I'll add tests to check if completion really works

2020-10-31 12:10 UTC, wvffle commented on index.js
> +            if (typeof matches[0].match === 'string') { resolve(matches.map(obj => obj.match)) }
Is this required? when does it return an object?

2020-10-31 14:32 UTC, wvffle commented on index.js
> +            if (typeof matches[0].match === 'string') { resolve(matches.map(obj => obj.match)) }
Okay, I see why

2020-10-31 14:48 UTC, wvffle commented
Hmm, the completion seemed to be partially broken due to PrismarineJS/flying-squid#457

2020-10-31 16:20 UTC, wvffle approved these changes

2020-10-31 16:20 UTC, merged